#!/bin/bash

#SBATCH --nodes=1
#SBATCH --time=4:00:00
#SBATCH --mem=140G
#SBATCH --ntasks=10
#SBATCH --qos=blanca-winters
#SBATCH --output=Combine_X_Y.log
#SBATCH --job-name=Combine_X_Y
#SBATCH --mail-type=ALL
#SBATCH --mail-user="rebecca.baiman@colorado.edu"

module purge
module load python
module load intel/16.0.3 
module load netcdf
module load impi/5.1.3.210
module load cdo/1.8.1


source /curc/sw/anaconda3/latest
conda activate research

python Combine_X_Y.py

