#!/bin/bash

#SBATCH --nodes=1
#SBATCH --time=2:00:00
#SBATCH --mem=40G
#SBATCH --ntasks=12
#SBATCH --qos=blanca-winters
#SBATCH --output=Make_data.log
#SBATCH --job-name=make_data
#SBATCH --mail-type=ALL
#SBATCH --mail-user="rebecca.baiman@colorado.edu"



module purge
module load python
module load gnu_parallel


source /curc/sw/anaconda3/latest
conda activate research

parallel -j $SLURM_NTASKS python Make_Y_data_3.py ::: {0..39}

