#!/bin/bash

#SBATCH --nodes=1
#SBATCH --time=12:00:00
#SBATCH --mem=120G
#SBATCH --ntasks=5
#SBATCH --qos=blanca-winters
#SBATCH --output=run_XGB.log
#SBATCH --job-name=run_xgb
#SBATCH --mail-type=ALL
#SBATCH --mail-user="rebecca.baiman@colorado.edu"

module purge
module load python
module load gnu_parallel

source /curc/sw/anaconda3/latest
conda activate ML

python run_XGboost_region.py

parallel -j $SLURM_NTASKS python run_XGboost_region.py ::: {0..9}